# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: java

script: mvn install -P uat

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

deploy:
  provider: openshift
  user: thelittlebighand@gmail.com
  password:
    secure: QKA0yzLSrxLbhmR1514UfA/TBypTRmz/Rk1djtlsa16qtqPnA78rzXnqGCjJ8jTu7I+zkf5NmwDNbiMVva/Syh9O7LUA6H1cRSba96UyQMOeubFWTTBMi1QTp1jCPtUNzw0liQiOENfAOWHpJn+8PAKJkoneOY/djzYrvDatnRSRIHyPKUH7aXE4q2+f9UJpJnOARrX/YD2kNvJ29spLuHKMYPm3yGrjXJdCXbL0qHArqilfuh6czYRWZ5SpYrCfaRzONEuAxAlIishhT43H+Q0D+02bmDycEGqu1dUZfrW0WHX1pnyzsg2fS2IjZc4WPob1HFGNGA73Naz4Hf9Dn2CbAgj8d73W1LaCv12Fgos3GAJ5/2eFNmbN0QHYcvQ+q4Vz2YWuCYhuuCnwfHxSCGLcyozrpZXF1DByDCPwtWh3hXOibsgmLq5We0B6r+xMqL64YTmAl02/xB2ti+Fo75EMz3ZOujju5LYz6IF5gZWJW71kw6DHho1lNVxQtCjjeDmkuD7aIfN7i3z12XQEDYb2xWBsRpl+Mw/2/m7xDV33ZM23+kS6uXURhvPmMwhBaU2ekHvblswSq11YP+DYOiGpr7CWsLs4lVmPVHgsKJq4zBz3cahGww/PJaEDPrylmUdW3KxOxLZbXZJw1f8ZERRoBeOJu6ft60XECtbCIUo=
  app: web
  domain: thelittlebighand
  on:
    repo: jaroslavpsenicka/bordylek
