# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: java

script: mvn install -P uat

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

deploy:
  provider: openshift
  user: thelittlebighand@gmail.com
  password:
    secure: HduCbBOCBAZxrDvKTzkQukWMz3lM+r5zoJ5j7VOJA1kv9iEMdTV+57tscVKAd/aZN+aNqhrGtz9WcxCi3rDcdnjmTA9/pUn/42mkFkGg7W+Z95IFAXut3ldjghBKsfFglkHKxBAoQ8xPuB76jWZlFIn5WXw+m0gJtVlVDQHUswgJL54a60uP3vBp4S1DvQ4p3pzQh9QPvxFg/cUIt4iJRi0yenh65zdwywgnboF9nhSC3cbMIyyPP33b0rJkRuJQVOB4YrCwRJ23XIsnpgMuSGsnDkKIP69qElvfmuqjOyoljciV1cCAHWuV6lCWGCClpuFlAgdb/uPPEseG8uLrB6f7B4h5YFJOiAYJVW9fGm07+xc1IK3rCo+3YJ88QwGuaW+g8VZTbY+5nzWhMGYidSPlDz2o3EePRp3mGD88icWOIxe2et0uMsAOfe1XsxiuzB5TfPujq1nIQtZl++MYemgB7BQxBgZCh6YkhgF1IWSw5UMT2FBUWeyi+SZ5sgQvL3QaJtr6VvHfplQJtexVOV2SK8O0o5QC3EF+WFWy4Ci6tuNArEbkxhMbVGOke5hloV46DS9dRxnDnM30wefPPA8bIRnyMaFMhYnZ1J2DVpWpL0HUrujp09fGerHOu5ub7Eey3yD162tlZhc54HINykwW0Y7HuVDClK0IW5CCV58=
  app: web
  domain: thelittlebighand
  on:
    repo: jaroslavpsenicka/bordylek

notifications:
  email:
    - jaroslav.psenicka@gmail.com
