package rules

import java.util.Date
import org.bordylek.mon.AlerterTest
import org.bordylek.service.model.metrics.*

global org.bordylek.mon.Alerter alerter

rule "Name"
 	dialect "mvel"
when
    oldCounter : Counter(name == "old")
then
    modify (oldCounter) {
     	name = "processed"
	}
end


rule "Age"
 	dialect "mvel"
when
    oldCounter : Counter(name == "very-old")
then
	alerter.info(this.getRule(), oldCounter, "too old")
end